baseURL = "https://github.com/rex-suresh/personalBlog/"
languageCode = "en-us"
theme = "ananke"
title = "Journey"


# theme = "Elfaseo"
# [params]
# 	sidebartitle = "Journey"
# 	sidebartagline = "Suresh's personal blog"

# Sidebar Menu	
	
# [[menu.main]]
#     name = "Get in touch"
#     url = "psureshk9@gmail.com"

# Footer Menu		
	
# [[menu.footer]]
#     name = "Home"
#     url = "/"

# [[menu.footer]]
#     name = "Contact"
#     url = "/contact.md"

	
# [[menu.footer]]
#     name = "Who Am I"
#     url = "/page/about"